services:
  # MySQL
  userdb:
    image: mysql:latest
    container_name: grpc_user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/userdb/data:/var/lib/mysql
      - ./docker/userdb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/userdb/sql:/docker-entrypoint-initdb.d
    ports:
      - 3308:3308
  organizationdb:
    image: mysql:latest
    container_name: grpc_organization
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/organizationdb/data:/var/lib/mysql
      - ./docker/organizationdb/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/organizationdb/sql:/docker-entrypoint-initdb.d
    ports:
      - 3307:3307
